import { useMemo, useState } from 'react'
import QuestionCard from './QuestionCard'

const CATEGORY_LABELS = {
  all: 'All',
  technical: 'Technical',
  coding: 'Coding',
  'system-design': 'System Design',
  behavioral: 'Behavioral',
  'role-specific': 'Role-Specific',
  'domain-knowledge': 'Domain',
}

export default function ResultsView({ result, onNewSearch }) {
  const [tab, setTab] = useState('all')
  const questions = result.questions || []

  const counts = useMemo(() => {
    const c = { all: questions.length }
    for (const q of questions) c[q.category] = (c[q.category] || 0) + 1
    return c
  }, [questions])

  const visible = tab === 'all' ? questions : questions.filter((q) => q.category === tab)
  const sourceCount = result.sources_read + (result.snippet_sources || 0)

  return (
    <div>
      {/* Header */}
      <div className="no-print mb-6 flex flex-wrap items-end justify-between gap-4">
        <div>
          <p className="text-xs font-medium uppercase tracking-wide text-accent-600">
            Interview prep sheet {result.from_cache && '· from cache'}
          </p>
          <h2 className="text-2xl font-semibold">
            {result.company} — {result.job_title}
          </h2>
          <p className="mt-1 text-sm text-slate-500">
            {questions.length} questions · {sourceCount} sources read
            {result.duration_s ? ` · ${Math.round(result.duration_s)}s` : ''}
          </p>
        </div>
        <div className="flex gap-2">
          <button onClick={() => downloadMarkdown(result)} className="btn-secondary">
            ⬇ Markdown
          </button>
          <button onClick={() => window.print()} className="btn-secondary">
            ⬇ PDF
          </button>
          <button
            onClick={onNewSearch}
            className="rounded-lg bg-accent-600 px-4 py-2 text-sm font-medium text-white hover:bg-accent-700"
          >
            New search
          </button>
        </div>
      </div>

      {result.limited_data && (
        <div className="no-print mb-6 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
          Limited public interview data for <span className="font-semibold">{result.company}</span> —
          showing role- and skill-based questions instead of company-reported ones. Sources shown
          are real, but describe the role/skills in general, not this company&apos;s process.
        </div>
      )}

      {/* Category tabs */}
      <div className="no-print mb-6 flex flex-wrap gap-2">
        {Object.entries(CATEGORY_LABELS).map(([key, label]) =>
          counts[key] ? (
            <button
              key={key}
              onClick={() => setTab(key)}
              className={`rounded-full px-4 py-1.5 text-sm font-medium transition ${
                tab === key
                  ? 'bg-accent-600 text-white'
                  : 'border border-slate-200 bg-white text-slate-600 hover:border-accent-500'
              }`}
            >
              {label} <span className="opacity-60">({counts[key]})</span>
            </button>
          ) : null,
        )}
      </div>

      <div className="no-print space-y-3">
        {visible.map((q, i) => (
          <QuestionCard key={`${tab}-${i}`} q={q} index={i + 1} />
        ))}
      </div>

      {/* Print-only expanded sheet (used by the PDF export) */}
      <PrintSheet result={result} />
    </div>
  )
}

function PrintSheet({ result }) {
  return (
    <div className="print-only">
      <h1 style={{ fontSize: 22, fontWeight: 700 }}>
        {result.company} — {result.job_title}: Interview Prep Sheet
      </h1>
      <p style={{ color: '#666', fontSize: 12, marginBottom: 16 }}>
        Generated by InterviewLens · {result.questions.length} questions
      </p>
      {result.questions.map((q, i) => (
        <div key={i} style={{ marginBottom: 18, breakInside: 'avoid' }}>
          <p style={{ fontWeight: 700, fontSize: 14 }}>
            {i + 1}. {q.question}{' '}
            <span style={{ fontWeight: 400, color: '#888', fontSize: 11 }}>
              [{q.category}
              {q.is_generic ? ' · generic' : ` · seen in ${q.frequency} source${q.frequency > 1 ? 's' : ''}`}]
            </span>
          </p>
          <p style={{ fontSize: 12.5, whiteSpace: 'pre-wrap', margin: '4px 0' }}>{q.answer}</p>
          {q.why_asked && (
            <p style={{ fontSize: 11.5, color: '#555' }}>
              <b>Why asked:</b> {q.why_asked}
            </p>
          )}
          {q.tips && (
            <p style={{ fontSize: 11.5, color: '#555' }}>
              <b>Tips:</b> {q.tips}
            </p>
          )}
          {q.sources?.length > 0 && (
            <p style={{ fontSize: 10.5, color: '#777', wordBreak: 'break-all' }}>
              Sources: {q.sources.join('  ·  ')}
            </p>
          )}
        </div>
      ))}
    </div>
  )
}

function downloadMarkdown(result) {
  const lines = [
    `# ${result.company} — ${result.job_title}: Interview Prep Sheet`,
    '',
    `> Generated by InterviewLens · ${result.questions.length} questions · ${result.sources_read} sources read`,
    '',
  ]
  if (result.limited_data) {
    lines.push(
      '> ⚠️ Limited public interview data for this company — questions marked *generic* are role/skill-based.',
      '',
    )
  }
  for (const [i, q] of result.questions.entries()) {
    const badge = q.is_generic ? 'generic' : `seen in ${q.frequency} source${q.frequency > 1 ? 's' : ''}`
    lines.push(`## ${i + 1}. ${q.question}`)
    lines.push(`*Category: ${q.category} · ${badge}*`, '')
    lines.push(q.answer, '')
    if (q.why_asked) lines.push(`**Why asked:** ${q.why_asked}`, '')
    if (q.tips) lines.push(`**Tips:** ${q.tips}`, '')
    if (q.sources?.length) {
      lines.push('**Sources:**')
      for (const s of q.sources) lines.push(`- ${s}`)
      lines.push('')
    }
  }
  const blob = new Blob([lines.join('\n')], { type: 'text/markdown' })
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = `${result.company}-${result.job_title}-prep`.replace(/[^a-z0-9-]+/gi, '-') + '.md'
  a.click()
  URL.revokeObjectURL(a.href)
}
